[package]
name = "order_matcher"
version = "0.1.0"
edition = "2021"

[dependencies]
primitive = { git = "https://github.com/Banyc/primitive.git", tag = "v0.0.58" }

[dev-dependencies]
rand = "0.8"

[profile.profiling]
inherits = "release"
debug = true
